import { useState } from 'react';
import { ArrowRight, Leaf, Moon, Sparkles, Users } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Button } from '../../components/ui/Button';
import { usePrototypeStore } from '../../store/usePrototypeStore';
import type { Recommendation } from '../../types';

const recommendationTemplates: Recommendation[] = [
  { id: 'journey-reset', title: 'Daily Breathing Sessions', type: 'program', reason: 'Short resets can help regulate stress and restore focus.', durationMinutes: 10, actionLabel: 'Explore Program' },
  { id: 'journey-sleep', title: 'Sleep Recovery Program', type: 'program', reason: 'A steadier evening routine can support energy and recovery.', durationMinutes: 15, actionLabel: 'Explore Program' },
  { id: 'journey-coach', title: 'Weekly Wellness Coaching', type: 'session', reason: 'A human conversation can turn patterns into a practical plan.', durationMinutes: 45, actionLabel: 'Book Session' },
];

export function RecommendationsPage() {
  const navigate = useNavigate();
  const { profile, latestStressMappingResult, assessmentResults, checkIns, wellnessPlan, recommendations, setRecommendations, addWellnessPlanItem } = usePrototypeStore();
  const [generated, setGenerated] = useState(recommendations.length > 0);
  const hasContext = Boolean(latestStressMappingResult || Object.keys(assessmentResults).length || checkIns.length);
  const generate = () => { const stress = latestStressMappingResult?.category ?? 'manageable'; const reason = `Based on your ${stress} stress pattern and ${wellnessPlan.length} plan activit${wellnessPlan.length === 1 ? 'y' : 'ies'}, these actions fit your current needs.`; setRecommendations(recommendationTemplates.map(item => ({ ...item, reason }))); setGenerated(true); };
  return <div className="mx-auto max-w-6xl space-y-6 pb-12 animate-in fade-in duration-500"><button onClick={() => navigate('/dashboard')} className="text-xs font-medium text-[var(--color-text-secondary)] hover:text-[var(--color-accent)]">← Back to Dashboard</button><section className="relative overflow-hidden rounded-2xl border border-[var(--color-brand-100)] bg-[var(--color-brand-50)] p-7"><div className="absolute -right-5 -top-10 text-[180px] text-[var(--color-brand-200)] opacity-40">⌁</div><div className="relative max-w-xl"><p className="mb-2 text-xs font-semibold uppercase tracking-[0.16em] text-[var(--color-brand-600)]">Personalized journey</p><h1 className="text-3xl font-semibold tracking-tight text-[var(--color-brand-950)]">Hello {profile.name.split(' ')[0]},</h1><p className="mt-3 text-sm leading-relaxed text-[var(--color-brand-800)]">Recommendations shaped by your assessments, daily check-ins, and progress.</p></div></section>{!hasContext ? <EmptyState navigate={navigate} /> : <><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">Your Recommended Journey</h2><p className="text-sm text-[var(--color-text-secondary)]">Generate an updated set as your wellbeing picture changes.</p></div><Button onClick={generate}>{generated ? 'Update Recommendations' : 'Generate Recommendations'} <Sparkles size={14} className="ml-2" /></Button></div>{!generated ? <div className="rounded-2xl border border-[var(--color-border)] bg-white p-8 text-center"><p className="text-sm text-[var(--color-text-secondary)]">Your latest information is ready to turn into practical next steps.</p><Button className="mt-4" onClick={generate}>Generate Recommendations</Button></div> : <div className="grid grid-cols-1 gap-4 md:grid-cols-3">{recommendations.map((item, index) => <RecommendationCard key={item.id} item={item} index={index} navigate={navigate} add={() => addWellnessPlanItem({ recommendationId: item.id, title: item.title, type: item.type })} />)}</div>}</>}</div>;
  }

  function EmptyState({ navigate }: { navigate: ReturnType<typeof useNavigate> }) { return <section className="rounded-2xl border border-[var(--color-border)] bg-white p-10 text-center shadow-[0_4px_20px_rgba(42,64,38,0.04)]"><Sparkles className="mx-auto text-[var(--color-brand-600)]" /><h2 className="mt-4 text-xl font-semibold">Build your first recommendation set</h2><p className="mx-auto mt-2 max-w-md text-sm text-[var(--color-text-secondary)]">Complete an assessment so SEIMEI can tailor your next steps to what you need today.</p><Button className="mt-5" onClick={() => navigate('/assessments')}>Go to Assessments <ArrowRight size={14} className="ml-2" /></Button></section>; }
  function RecommendationCard({ item, index, navigate, add }: { item: Recommendation; index: number; navigate: ReturnType<typeof useNavigate>; add: () => void }) { const Icon = index === 0 ? Leaf : index === 1 ? Moon : Users; return <section className="rounded-2xl border border-[var(--color-border)] bg-white p-5 shadow-[0_4px_20px_rgba(42,64,38,0.04)]"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-[var(--color-brand-50)] text-[var(--color-brand-600)]"><Icon size={21} /></span><p className="mt-5 text-[10px] font-semibold uppercase tracking-[0.14em] text-[var(--color-text-secondary)]">Week {index + 1}</p><h3 className="mt-2 text-base font-semibold">{item.title}</h3><p className="mt-2 min-h-12 text-sm leading-relaxed text-[var(--color-text-secondary)]">{item.reason}</p><div className="mt-5 flex gap-2"><Button size="sm" onClick={() => item.type === 'session' ? navigate('/programs/coaching') : navigate('/programs')}>{item.actionLabel}</Button><Button size="sm" variant="outline" onClick={add}>Add to Plan</Button></div></section>; }
