import { useState } from 'react';
import { ArrowRight, Flame, Heart, Leaf, ListTodo, Sparkles } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Button } from '../../components/ui/Button';
import { usePrototypeStore } from '../../store/usePrototypeStore';
import { getNextAction, getWellnessPlanProgress } from '../../lib/wellnessPlanLogic';
import { WellnessPlanItemCard } from './WellnessPlanItemCard';
import { NextActionCard } from './NextActionCard';

export function WellnessPlanPage() {
  const navigate = useNavigate();
  const plan = usePrototypeStore(state => state.wellnessPlan);
  const [tab, setTab] = useState('My Plan');
  const { total, completed, percentage, activeItems, completedItems } = getWellnessPlanProgress(plan);
  const nextAction = getNextAction(activeItems);
  const visibleItems = tab === 'Completed' ? completedItems : tab === 'All Activities' ? plan : activeItems;
  return <div className="mx-auto max-w-6xl space-y-5 pb-12 animate-in fade-in duration-500">
    <header><p className="mb-1 text-xs font-medium uppercase tracking-[0.16em] text-[var(--color-brand-600)]">Your personal rhythm</p><h1 className="text-3xl font-semibold tracking-tight">My Wellness Plan</h1><p className="mt-1 text-sm text-[var(--color-text-secondary)]">Your personalized action plan to help you reset, recover and thrive.</p></header>
    <div className="grid grid-cols-1 gap-4 xl:grid-cols-[1.15fr_1.35fr_1fr]"><ProgressCard completed={completed} total={total} percentage={percentage} />{nextAction ? <NextActionCard item={nextAction} /> : <EmptyNextAction navigate={navigate} />}<section className="rounded-2xl border border-[var(--color-border)] bg-white p-5 shadow-[0_4px_20px_rgba(42,64,38,0.04)]"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-[#fff0df] text-[#ed7e28]"><Flame size={24} /></span><div><p className="text-xs text-[var(--color-text-secondary)]">Consistency Streak</p><strong className="text-2xl">7 <span className="text-sm font-medium">days</span></strong></div></div><p className="mt-3 text-xs text-[var(--color-text-secondary)]">Keep it going!</p><div className="mt-4 flex justify-between">{['M', 'T', 'W', 'T', 'F', 'S', 'S'].map((day, index) => <span key={`${day}-${index}`} className={`flex h-6 w-6 items-center justify-center rounded-full text-[10px] font-semibold ${index < 6 ? 'bg-[var(--color-brand-600)] text-white' : 'border border-[var(--color-border)] text-[var(--color-text-secondary)]'}`}>{index < 6 ? '✓' : day}</span>)}</div></section></div>
    <div className="grid grid-cols-1 gap-5 xl:grid-cols-[minmax(0,1fr)_270px]"><section className="rounded-2xl border border-[var(--color-border)] bg-white shadow-[0_4px_20px_rgba(42,64,38,0.04)]"><div className="flex gap-6 border-b border-[var(--color-border)] px-5 pt-4">{['My Plan', 'Completed', 'All Activities'].map(item => <button key={item} onClick={() => setTab(item)} className={`border-b-2 pb-3 text-xs font-semibold ${tab === item ? 'border-[var(--color-accent)] text-[var(--color-accent)]' : 'border-transparent text-[var(--color-text-secondary)]'}`}>{item}{item !== 'My Plan' && <span className="ml-1 font-normal">({item === 'Completed' ? completedItems.length : total})</span>}</button>)}</div><div className="p-4">{visibleItems.length ? <div className="space-y-3">{visibleItems.map(item => <WellnessPlanItemCard key={item.id} item={item} />)}</div> : <div className="p-10 text-center"><ListTodo className="mx-auto text-[var(--color-brand-500)]" /><p className="mt-3 text-sm text-[var(--color-text-secondary)]">No activities in this view yet.</p><Button className="mt-4" onClick={() => navigate('/recommendations')}>Explore recommendations</Button></div>}</div></section><aside className="space-y-4"><SupportCard icon={Sparkles} title="Plan Insights" text={`You've completed ${completed} activities so far. Small consistency creates lasting change.`} /><SupportCard icon={Leaf} title="Tips for You" text="Taking short breaks can improve focus, reduce stress and boost productivity." /><SupportCard icon={Heart} title="Need More Support?" text="Explore programs and resources curated for you." action={() => navigate('/resources')} /></aside></div>
  </div>;
}

function ProgressCard({ completed, total, percentage }: { completed: number; total: number; percentage: number }) { const radius = 42; const length = 2 * Math.PI * radius; return <section className="rounded-2xl border border-[var(--color-border)] bg-white p-5 shadow-[0_4px_20px_rgba(42,64,38,0.04)]"><h2 className="text-sm font-semibold">Your Progress</h2><div className="mt-3 flex items-center gap-4"><div className="relative h-28 w-28 shrink-0"><svg className="h-full w-full -rotate-90" viewBox="0 0 100 100"><circle cx="50" cy="50" r={radius} fill="none" stroke="#e8ede5" strokeWidth="8" /><circle cx="50" cy="50" r={radius} fill="none" stroke="var(--color-brand-600)" strokeWidth="8" strokeLinecap="round" strokeDasharray={length} strokeDashoffset={length - percentage / 100 * length} /></svg><span className="absolute inset-0 flex flex-col items-center justify-center text-xl font-semibold">{percentage}%<small className="text-[9px] font-normal text-[var(--color-text-secondary)]">Complete</small></span></div><div className="space-y-2 text-xs"><p><i className="mr-2 inline-block h-2 w-2 rounded-full bg-[var(--color-brand-600)]" />Completed <b className="float-right ml-6">{completed}</b></p><p><i className="mr-2 inline-block h-2 w-2 rounded-full bg-[#f0aa23]" />In Progress <b className="float-right ml-6">{Math.max(0, total - completed - 1)}</b></p><p><i className="mr-2 inline-block h-2 w-2 rounded-full bg-[#c6cbc5]" />Remaining <b className="float-right ml-6">{Math.max(0, total - completed)}</b></p></div></div><p className="mt-2 text-right text-[10px] text-[var(--color-text-secondary)]">Total Activities <b className="ml-4 text-[var(--color-text-primary)]">{total}</b></p></section>; }
function EmptyNextAction({ navigate }: { navigate: ReturnType<typeof useNavigate> }) { return <section className="rounded-2xl border border-[var(--color-border)] bg-white p-5 shadow-[0_4px_20px_rgba(42,64,38,0.04)]"><h2 className="text-sm font-semibold">Next Action</h2><p className="mt-5 text-sm text-[var(--color-text-secondary)]">Your plan is clear. Add a new supportive action from Recommendations.</p><Button size="sm" className="mt-5" onClick={() => navigate('/recommendations')}>Explore <ArrowRight size={13} className="ml-1" /></Button></section>; }
function SupportCard({ icon: Icon, title, text, action }: { icon: typeof Leaf; title: string; text: string; action?: () => void }) { return <section className="rounded-2xl border border-[var(--color-border)] bg-white p-4 shadow-[0_4px_20px_rgba(42,64,38,0.03)]"><div className="flex items-center gap-2"><Icon size={17} className="text-[var(--color-brand-600)]" /><h2 className="text-sm font-semibold">{title}</h2></div><p className="mt-3 text-xs leading-relaxed text-[var(--color-text-secondary)]">{text}</p>{action && <button onClick={action} className="mt-3 text-xs font-semibold text-[var(--color-accent)]">Explore resources <ArrowRight size={13} className="ml-1 inline" /></button>}</section>; }
